[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    cloudName = "triplens"
    deliveryType = "fetch"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
